### ISSUE TITLE
Push the TOML configuration as default

### ISSUE THREAD

**Issue by azerupi** [azerupi/mdBook#285]
As part of #275 we would like to push the TOML configuration as the default and deprecate the JSON config. We are not going to remove the JSON config just yet, but we are going to show a deprecation warning.

Here are some the things that need to happen:

- [x] Parity between the JSON config and TOML config
- [x] Move and rename `dest`, `src` and `theme_path` to
  ```toml
  source = "path/to/sources"
  
  [output.html]
  destination = "path/to/output"
  theme = "path/to/directory"
  ```
- [x] Add a key for an additional custom stylesheet #266 #178 
  ```toml
  [output.html]
  additional-css = ["path/to/file.css"]
  ```
- [x] Add tests for each config key
- [x] Reading the config should not overwrite unspecified keys #240 
- [x] Document the TOML config
