### ISSUE TITLE
Header links now are always black instead of the theme color

### ISSUE THREAD

**Issue by mdinger** [azerupi/mdBook#89]
In the [readme](http://azerupi.github.io/mdBook/README.html), the *coal theme* used to determine the **header** colors but now it is always black. This css currently determines the color:

```css
a h1, a h2, a h3, a h4, a h5 {
    color: #000;
}
```

It used to be:

```css
.coal {
    color: #98A3AD;
}
```

I'm guessing this was caused by https://github.com/azerupi/mdBook/pull/79. This happens in all themes. Black doesn't look bad in light themes but definitely doesn't work with the dark themes.

Also, it underlines blue on highlight which seems to be a minor bug.

cc @asolove
